use_frameworks!

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'PPKit_Example' do
  pod 'PPKitMaple', :path => '../'

  target 'PPKit_Tests' do
    inherit! :search_paths

    
  end
end
